### ISSUE TITLE
ieee754 conversion

### ISSUE THREAD

**Issue by kalaszlo** [dvsu/sps30#2]
Hi.

I think there is a problem with your ieee754 conversion function. I observed that particulate size smaller than 1 um is still displayed as 1+ um sized particle. We are talking about the case when the exponent is < 0. In that case the resulting number should be divided with the power of 2, of the absolute value of the exponent. I hope it is clear what i mean to say, and am i right. :) I modified the sps30.py (ieee754_number_conversion function) in the way seen below:

 #        exp = 0 if exp < 0 else exp ------ would be
         divider = 0
         if (exp < 0):
             divider = abs(exp)
             exp = 0 

 #        return round((((-1)**(sign) * real) + dec), 3) ------ would be
         if (divider == 0):
             return (round((((-1)**(sign) * real) + dec), 3))
         else:
             return ((round((((-1)**(sign) * real) + dec), 3) / pow(2, divider)))

Probably there is a more elegant way to do this, but it is working.
Regards,
    Laszlo

**Comment by dvsu** [comment]
Thanks @kalaszlo ! Spot on! The calculation result will always be "clipped" at 1.xxx when `exp` is less than zero.  Regardless the values of `decimal` and `sign`, the expected return value is either `1.xxx` or `-1.xxx` based on the below formula.

```python
return round((((-1)**(sign) * real) + dec), 3)
```

I agree with the addition of `divider` variable, so the return value can go between 0 and 1.

Feel free to submit a pull request :) 

Dave

**Comment by dvsu** [comment]
I have implemented the fix to make sure this repo is updated. Thanks again @kalaszlo !
