### ISSUE TITLE
Extension : write_auto_cleaning_interval_days() function

### ISSUE THREAD

**Issue by pklosko** [dvsu/sps30#3]
In sps30.py :
    def write_auto_cleaning_interval_days(self, days: int) -> int:
        seconds = days * 86400 # 1day = 86400sec
        interval = []
        interval.append((seconds & 0xff000000) >> 24)
        interval.append((seconds & 0x00ff0000) >> 16)
        interval.append((seconds & 0x0000ff00) >> 8)
        interval.append(seconds & 0x000000ff)
        data = CMD_AUTO_CLEANING_INTERVAL
        data.extend([interval[0], interval[1]])
        data.append(self.crc_calc(data[2:4]))
        data.extend([interval[2], interval[3]])
        data.append(self.crc_calc(data[5:7]))
        self.i2c.write(data)
        sleep(0.05)
        return self.read_auto_cleaning_interval()

Usage (example.py):
   ...
    pm_sensor = SPS30(3)  #Im using i3c_bus3
    ...
    print(f"Set auto cleaning interval: {pm_sensor.write_auto_cleaning_interval_days(2)}s")

**Comment by dvsu** [comment]
Hi @pklosko thank you for the suggestion. I will implement this function in the next commit.
